name: send-patch

on:
  schedule:
    - cron: "*/8 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    # Injection du secret pour tout le job
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Cache Playwright
      - name: Cache Playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}

      # Restore last_sent.txt (clé dynamique + restore-keys)
      - name: Restore last_sent cache
        uses: actions/cache@v4
        with:
          path: last_sent.txt
          key: last-sent-${{ github.run_id }}
          restore-keys: |
            last-sent-

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run bot
        run: python main.py

      # Save last_sent.txt (clé dynamique)
      - name: Save last_sent cache
        if: always()
        uses: actions/cache@v4
        with:
          path: last_sent.txt
          key: last-sent-${{ github.run_id }}
